# Generated by Django 5.0.10 on 2025-06-29 15:45

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('extras', '0121_customfield_related_object_filter'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('cabletermination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dcim.cabletermination')),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('interfaceconfig', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(default='a-patcher', max_length=50)),
                ('legacy_id', models.IntegerField()),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugs', to='tenancy.contact')),
                ('ip_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plug', to='ipam.ipaddress')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plugs', to='dcim.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plugs', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plugs', to='tenancy.tenant')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugs', to='ipam.vlan')),
            ],
            options={
                'verbose_name': 'Prise',
                'verbose_name_plural': 'Prises',
                'ordering': ('site', 'location', 'name'),
            },
            bases=('dcim.cabletermination', models.Model),
        ),
        migrations.AddConstraint(
            model_name='plug',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='plugsbox_plug_unique_site_name'),
        ),
    ]
