# Generated by Django 5.2.3 on 2025-06-30 11:24

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('extras', '0129_fix_script_paths'),
        ('ipam', '0081_remove_service_device_virtual_machine_add_parent_gfk_index'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('interfaceconfig', models.CharField(default='mab', max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(default='a-patcher', max_length=50)),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugs', to='tenancy.contact')),
                ('ip_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plug', to='ipam.ipaddress')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plugs', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plugs', to='tenancy.tenant')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugs', to='ipam.vlan')),
            ],
            options={
                'verbose_name': 'Prise',
                'verbose_name_plural': 'Prises',
                'ordering': ('site', 'location', 'name'),
                'constraints': [models.UniqueConstraint(fields=('site', 'name'), name='plugsbox_plug_unique_site_name')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
