# Generated by Django 5.2.3 on 2025-06-30 12:45

import plugsbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugsbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plug',
            name='activation_date',
            field=models.DateField(default=plugsbox.models.default_activation_date),
        ),
    ]
