# Generated by Django 5.2.3 on 2025-07-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugsbox', '0001_initial'),
        ('tenancy', '0020_remove_contactgroupmembership'),
        ('users', '0009_update_group_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionnaire',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestionnaire', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='gestionnaire',
            name='user_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestionnaire', to='users.group'),
        ),
    ]
