# Generated by Django 5.2.3 on 2025-06-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugsbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plug',
            name='location',
            field=models.CharField(blank=True, default='toto', max_length=200),
            preserve_default=False,
        ),
    ]
