# Generated by Django 5.2.3 on 2025-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugsbox', '0002_plug_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plug',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
