# Generated by Django 5.2.3 on 2025-06-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('plugsbox', '0003_alter_plug_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plug',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugs', to='dcim.interface'),
        ),
        migrations.AddField(
            model_name='plug',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugs', to='dcim.device'),
        ),
    ]
