# Generated by Django 5.2.3 on 2025-06-30 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('plugsbox', '0004_plug_interface_plug_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='plug',
            name='cable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plug_connection', to='dcim.cable'),
        ),
        migrations.AddField(
            model_name='plug',
            name='user_interface',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plug_user_side', to='dcim.interface'),
        ),
    ]
